import Link from 'next/link';

export default function MethodologyPage() {
  return (
    <div className="min-h-screen bg-background">
      <header className="border-b border-border">
        <div className="mx-auto max-w-3xl px-4 h-14 flex items-center">
          <Link
            href="/a"
            className="text-[13px] text-muted-foreground hover:text-foreground transition-colors flex items-center gap-1.5"
          >
            <svg className="h-3.5 w-3.5" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
              <path d="M15 19l-7-7 7-7" />
            </svg>
            Feed
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-4 py-10">
        <h1 className="font-serif text-[2rem] leading-[1.2] tracking-tight text-foreground">
          Methodology &amp; Sources
        </h1>
        <p className="mt-4 text-[15px] leading-[1.7] text-muted-foreground">
          StemCell Pulse aggregates, verifies, and summarizes stem cell research from
          peer-reviewed journals, clinical trial registries, and regulatory bodies. Our goal
          is to deliver trustworthy, timely intelligence to researchers and clinicians.
        </p>

        <div className="my-8 h-px bg-border-subtle" />

        <section className="space-y-8">
          <div>
            <h2 className="text-[11px] font-mono uppercase tracking-[0.08em] text-muted-foreground/60 mb-3">
              Data Sources
            </h2>
            <ul className="space-y-2 text-[14px] leading-[1.6] text-foreground">
              <li><strong>Journals:</strong> PubMed, Nature, Cell, Science, The Lancet, NEJM, and 40+ high-impact biomedical journals monitored daily via API.</li>
              <li><strong>Clinical Trials:</strong> ClinicalTrials.gov, EU Clinical Trials Register, and ICTRP. Updated weekly.</li>
              <li><strong>Regulatory:</strong> FDA press releases, EMA PRIME designations, PMDA approvals, and Health Canada notices.</li>
              <li><strong>Preprints:</strong> bioRxiv and medRxiv stem cell preprints, flagged with a Preprint evidence badge.</li>
            </ul>
          </div>

          <div>
            <h2 className="text-[11px] font-mono uppercase tracking-[0.08em] text-muted-foreground/60 mb-3">
              Evidence Classification
            </h2>
            <ul className="space-y-2 text-[14px] leading-[1.6] text-foreground">
              <li><strong>Peer-Reviewed:</strong> Published in a journal with formal peer review.</li>
              <li><strong>Preprint:</strong> Deposited on a preprint server. Not yet peer-reviewed.</li>
              <li><strong>Clinical Trial:</strong> Registered interventional study with defined endpoints.</li>
              <li><strong>Meta-Analysis:</strong> Systematic review pooling data from multiple studies.</li>
              <li><strong>Regulatory:</strong> Official action by a regulatory authority (approval, designation, guidance).</li>
            </ul>
          </div>

          <div>
            <h2 className="text-[11px] font-mono uppercase tracking-[0.08em] text-muted-foreground/60 mb-3">
              Summarization
            </h2>
            <p className="text-[14px] leading-[1.6] text-foreground">
              Key findings are generated by AI from paper abstracts and full text when available,
              then reviewed for accuracy. We prioritize reporting specific results (effect sizes,
              sample sizes, statistical significance) over general claims. Every item links back
              to its original source.
            </p>
          </div>

          <div>
            <h2 className="text-[11px] font-mono uppercase tracking-[0.08em] text-muted-foreground/60 mb-3">
              Ranking
            </h2>
            <p className="text-[14px] leading-[1.6] text-foreground">
              Items are displayed in reverse chronological order. We do not apply editorial ranking
              or algorithmic sorting. What you see is the unfiltered stream, organized by time.
            </p>
          </div>
        </section>

        <div className="mt-12 pt-6 border-t border-border-subtle">
          <p className="text-[12px] text-muted-foreground/50 font-mono">
            Last updated: February 2026. Questions? Contact research@stemcellpulse.com
          </p>
        </div>
      </main>
    </div>
  );
}
