import Link from 'next/link';

const sections = [
  {
    title: 'Data Sources',
    items: [
      'PubMed, Nature, Cell, Science, The Lancet, NEJM, and 40+ high-impact biomedical journals monitored daily via API.',
      'ClinicalTrials.gov, EU Clinical Trials Register, and ICTRP. Updated weekly.',
      'FDA, EMA, PMDA regulatory press releases and designations.',
      'bioRxiv and medRxiv preprints, flagged with evidence badges.',
    ],
  },
  {
    title: 'Evidence Classification',
    items: [
      'Peer-Reviewed — Published in a journal with formal peer review.',
      'Preprint — Deposited on a preprint server. Not yet peer-reviewed.',
      'Clinical Trial — Registered interventional study with defined endpoints.',
      'Meta-Analysis — Systematic review pooling data from multiple studies.',
      'Regulatory — Official action by a regulatory authority.',
    ],
  },
  {
    title: 'Summarization',
    items: [
      'Key findings generated by AI from abstracts and full text, reviewed for accuracy.',
      'Prioritizes specific results: effect sizes, sample sizes, statistical significance.',
      'Every item links to its original source for verification.',
    ],
  },
  {
    title: 'Ranking & Display',
    items: [
      'Default sort is reverse chronological. No editorial ranking or algorithmic bias.',
      'Filter by source type (journals, clinical trials, regulatory) or search by keyword.',
      'Evidence level is always visible without hover or click.',
    ],
  },
];

export default function MethodologyPage() {
  return (
    <div className="min-h-screen bg-background">
      <header className="sticky top-0 z-40 border-b border-border-subtle bg-background/80 backdrop-blur-md supports-[backdrop-filter]:bg-background/60">
        <div className="mx-auto max-w-3xl px-4 sm:px-6 h-14 flex items-center">
          <Link
            href="/c"
            className="text-[13px] text-muted-foreground hover:text-foreground transition-colors flex items-center gap-1.5 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/30 rounded-md px-1"
          >
            <svg className="h-3.5 w-3.5" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
              <path d="M15 19l-7-7 7-7" />
            </svg>
            Feed
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-4 sm:px-6 py-10">
        <p className="text-[10.5px] font-mono uppercase tracking-[0.1em] text-muted-foreground/50 mb-3">
          About
        </p>
        <h1 className="font-serif text-[1.875rem] sm:text-[2.125rem] leading-[1.2] tracking-tight text-foreground">
          Sources &amp; Methodology
        </h1>
        <p className="mt-4 text-[15px] leading-[1.65] text-muted-foreground">
          StemCell Pulse aggregates, verifies, and summarizes stem cell research from
          peer-reviewed journals, clinical trial registries, and regulatory bodies. Every item
          links directly to its primary source.
        </p>

        <div className="mt-10 space-y-4">
          {sections.map(({ title, items }) => (
            <div key={title} className="rounded-lg border border-border-subtle bg-card p-5">
              <h2 className="text-[10.5px] font-mono uppercase tracking-[0.08em] text-muted-foreground/40 mb-3">
                {title}
              </h2>
              <ul className="space-y-2.5">
                {items.map((text, i) => (
                  <li key={i} className="flex gap-2.5 text-[14px] leading-[1.6] text-foreground">
                    <span className="text-muted-foreground/20 mt-0.5 shrink-0">—</span>
                    {text}
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>

        <div className="mt-10 pt-6 border-t border-border-subtle">
          <p className="text-[11px] text-muted-foreground/30 font-mono">
            Last updated: February 2026 · research@stemcellpulse.com
          </p>
        </div>
      </main>
    </div>
  );
}
