import Link from 'next/link';

const sections = [
  {
    title: 'Data Sources',
    items: [
      'PubMed, Nature, Cell, Science, The Lancet, NEJM, and 40+ high-impact biomedical journals monitored daily via API.',
      'ClinicalTrials.gov, EU Clinical Trials Register, and ICTRP. Updated weekly.',
      'FDA, EMA, PMDA regulatory press releases and designations.',
      'bioRxiv and medRxiv preprints, flagged with evidence badges.',
    ],
  },
  {
    title: 'Evidence Classification',
    items: [
      'Peer-Reviewed — Published in a journal with formal peer review.',
      'Preprint — Deposited on a preprint server. Not yet peer-reviewed.',
      'Clinical Trial — Registered interventional study with defined endpoints.',
      'Meta-Analysis — Systematic review pooling data from multiple studies.',
      'Regulatory — Official action by a regulatory authority.',
    ],
  },
  {
    title: 'Summarization',
    items: [
      'Key findings generated by AI from abstracts and full text, reviewed for accuracy.',
      'Prioritizes specific results: effect sizes, sample sizes, statistical significance.',
      'Every item links to its original source for verification.',
    ],
  },
  {
    title: 'Ranking',
    items: [
      'Default sort is reverse chronological. No editorial ranking or algorithmic bias.',
      'Filter by source type or search by keyword.',
    ],
  },
];

export default function MethodologyPage() {
  return (
    <div className="min-h-screen bg-[#fafaf9] text-gray-900 selection:bg-teal-500/15">
      <div className="fixed inset-0 overflow-hidden pointer-events-none" aria-hidden="true">
        <div className="absolute -top-[25%] left-[25%] w-[45%] h-[45%] rounded-full bg-teal-400/[0.02] blur-[100px]" />
      </div>

      <div className="relative z-10">
        <header className="sticky top-0 z-40 border-b border-gray-200/60 bg-[#fafaf9]/70 backdrop-blur-xl supports-[backdrop-filter]:bg-[#fafaf9]/60">
          <div className="mx-auto max-w-3xl px-4 sm:px-6 h-14 flex items-center">
            <Link href="/e" className="text-[13px] text-gray-400 hover:text-gray-700 transition-colors flex items-center gap-1.5">
              <svg className="h-3.5 w-3.5" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
                <path d="M15 19l-7-7 7-7" />
              </svg>
              Feed
            </Link>
          </div>
        </header>

        <main className="mx-auto max-w-3xl px-4 sm:px-6 py-12">
          <p className="text-[10px] font-mono uppercase tracking-[0.1em] text-teal-600/50 mb-3">About</p>
          <h1 className="text-[1.875rem] sm:text-[2.25rem] font-semibold leading-[1.15] tracking-tight text-gray-900">
            Sources &amp; Methodology
          </h1>
          <p className="mt-4 text-[15px] leading-[1.65] text-gray-500">
            StemCell Pulse aggregates, verifies, and summarizes stem cell research. Every item links directly to its primary source.
          </p>

          <div className="mt-10 space-y-3">
            {sections.map(({ title, items }) => (
              <div key={title} className="rounded-2xl border border-gray-200/60 bg-white p-5 shadow-[0_1px_4px_rgba(0,0,0,0.02)]">
                <h2 className="text-[10px] font-mono uppercase tracking-[0.1em] text-gray-400 mb-3">{title}</h2>
                <ul className="space-y-2.5">
                  {items.map((text, i) => (
                    <li key={i} className="flex gap-2.5 text-[14px] leading-[1.6] text-gray-700">
                      <span className="text-gray-300 mt-0.5 shrink-0">—</span>
                      {text}
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>

          <div className="mt-10 pt-6 border-t border-gray-200/60">
            <p className="text-[11px] text-gray-300 font-mono">
              Last updated: February 2026 · research@stemcellpulse.com
            </p>
          </div>
        </main>
      </div>
    </div>
  );
}
