import Link from 'next/link';
import { Header } from '@/components/layout/Header';
import { Footer } from '@/components/layout/Footer';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Sources & Methodology | StemCell Pulse',
  description: 'How StemCell Pulse aggregates, verifies, and summarizes stem cell research from peer-reviewed journals, clinical trial registries, and regulatory bodies.',
};

export default function MethodologyPage() {
  return (
    <div className="flex min-h-screen flex-col">
      <Header />
      <main className="flex-1">
        <div className="mx-auto max-w-3xl px-4 sm:px-6 py-10">
          {/* Back link */}
          <Link
            href="/"
            className="inline-flex items-center gap-1.5 text-[13px] text-muted-foreground hover:text-foreground transition-colors mb-8"
          >
            <svg className="h-3.5 w-3.5" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
              <path d="M15 19l-7-7 7-7" />
            </svg>
            Back to Feed
          </Link>

          <h1 className="text-[1.75rem] font-semibold leading-[1.25] tracking-tight text-foreground">
            Sources &amp; Methodology
          </h1>
          <p className="mt-4 text-[15px] leading-[1.65] text-muted-foreground">
            StemCell Pulse aggregates, verifies, and summarizes stem cell research from
            peer-reviewed journals, clinical trial registries, and regulatory bodies. Every item
            links directly to its primary source.
          </p>

          <div className="mt-8 space-y-6">
            {[
              {
                title: 'Data Sources',
                items: [
                  'PubMed, Nature, Cell, Science, The Lancet, NEJM, and 40+ high-impact biomedical journals monitored daily via API.',
                  'ClinicalTrials.gov, EU Clinical Trials Register, and ICTRP. Updated weekly.',
                  'FDA, EMA, PMDA regulatory press releases and designations.',
                  'bioRxiv and medRxiv preprints, flagged with evidence badges.',
                ],
              },
              {
                title: 'Evidence Classification',
                items: [
                  'Peer-Reviewed: Published in a journal with formal peer review.',
                  'Preprint: Deposited on a preprint server. Not yet peer-reviewed.',
                  'Clinical Trial: Registered interventional study with defined endpoints.',
                  'Meta-Analysis: Systematic review pooling data from multiple studies.',
                  'Regulatory: Official action by a regulatory authority.',
                ],
              },
              {
                title: 'Summarization',
                items: [
                  'Key findings generated by AI from abstracts and full text, reviewed for accuracy.',
                  'We prioritize reporting specific results: effect sizes, sample sizes, statistical significance.',
                  'Every item links to its original source for verification.',
                ],
              },
              {
                title: 'Ranking',
                items: [
                  'Default sort is reverse chronological. No editorial ranking or algorithmic bias.',
                  'Filter by source type, search by keyword, or sort by journal.',
                ],
              },
            ].map(({ title, items }) => (
              <div key={title} className="rounded-lg border border-border-subtle bg-card p-5">
                <h2 className="text-[11px] font-mono uppercase tracking-[0.06em] text-muted-foreground/50 mb-3">
                  {title}
                </h2>
                <ul className="space-y-2">
                  {items.map((text, i) => (
                    <li key={i} className="flex gap-2 text-[14px] leading-[1.6] text-foreground">
                      <span className="text-muted-foreground/30 mt-0.5 shrink-0">&mdash;</span>
                      {text}
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>

          <div className="mt-10 pt-5 border-t border-border-subtle">
            <p className="text-[11px] text-muted-foreground/40 font-mono">
              Last updated: February 2026 &middot; research@stemcellpulse.com
            </p>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}
